# Generated by Django 4.2.7 on 2024-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images\\icons\\profile.png', null=True, upload_to='profile/image'),
        ),
    ]
