# Generated by Django 4.2.7 on 2024-03-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
    ]
