# Generated by Django 4.2.7 on 2024-03-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('number', models.TextField(verbose_name='شماره همراه')),
                ('email', models.TextField(verbose_name='ایمیل')),
                ('instagram', models.URLField(verbose_name='اینستاگرام')),
                ('telegram', models.URLField(verbose_name='تلگرام')),
                ('whatsapp', models.URLField(verbose_name='واتساپ')),
            ],
            options={
                'verbose_name': 'پل ارتباطی',
                'verbose_name_plural': 'پل های ارتباطی',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('created_an', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دریافت پیغام')),
            ],
            options={
                'verbose_name': 'پیغام',
                'verbose_name_plural': 'پیغام ها',
            },
        ),
    ]
