# Generated by Django 4.2.7 on 2024-03-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'پل ارتباطی', 'verbose_name_plural': 'پل های ارتباطی'},
        ),
    ]
