# Generated by Django 4.2.7 on 2024-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.TextField(max_length=11, verbose_name='شماره همراه'),
        ),
    ]
