# Generated by Django 4.2.7 on 2023-12-21 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0014_alter_article_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('A', 'farzad'), ('B', 'ali'), ('C', 'mamad')], help_text='bayad yek matn benevisid', max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(help_text='kodam user?', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
