# Generated by Django 4.2.7 on 2023-12-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0015_alter_article_body_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('A', 'farzad'), ('B', 'ali'), ('C', 'mamad')], default='B', help_text='bayad yek matn benevisid', max_length=70),
        ),
    ]
