# Generated by Django 4.2.7 on 2023-12-22 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0020_category_alter_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 22, 16, 33, 18, 149156, tzinfo=datetime.timezone.utc)),
        ),
    ]
