# Generated by Django 4.2.7 on 2023-12-23 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 23, 18, 37, 32, 786872, tzinfo=datetime.timezone.utc)),
        ),
    ]
