# Generated by Django 4.2.7 on 2023-12-23 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0023_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='days_left',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 23, 19, 30, 54, 321110, tzinfo=datetime.timezone.utc)),
        ),
    ]
