# Generated by Django 4.2.7 on 2023-12-26 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0024_article_days_left_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='testeman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forup', models.BinaryField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 13, 43, 45, 853971, tzinfo=datetime.timezone.utc)),
        ),
    ]
