# Generated by Django 4.2.7 on 2023-12-26 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0026_alter_article_pub_date_alter_testeman_forup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testeman',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 14, 10, 5, 989771, tzinfo=datetime.timezone.utc)),
        ),
    ]
