# Generated by Django 4.2.7 on 2023-12-28 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0027_delete_testeman_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=49)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 11, 42, 41, 354924, tzinfo=datetime.timezone.utc)),
        ),
    ]
