# Generated by Django 4.2.7 on 2023-12-28 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0028_test_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 11, 54, 35, 74062, tzinfo=datetime.timezone.utc)),
        ),
    ]
