# Generated by Django 4.2.7 on 2023-12-29 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0030_delete_test_remove_article_days_left_article_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 29, 9, 41, 3, 562162, tzinfo=datetime.timezone.utc)),
        ),
    ]
