# Generated by Django 4.2.7 on 2024-01-01 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0031_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 18, 30, 4, 922625, tzinfo=datetime.timezone.utc)),
        ),
    ]
