# Generated by Django 4.2.7 on 2024-01-31 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0033_alter_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testforsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 13, 29, 51, 144747, tzinfo=datetime.timezone.utc)),
        ),
    ]
