# Generated by Django 4.2.7 on 2024-02-02 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0036_delete_testforsave_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 14, 33, 54, 174041, tzinfo=datetime.timezone.utc)),
        ),
    ]
