# Generated by Django 4.2.7 on 2024-02-07 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0039_alter_article_category_alter_article_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 7, 17, 29, 33, 888916, tzinfo=datetime.timezone.utc)),
        ),
    ]
