# Generated by Django 4.2.7 on 2024-02-18 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0042_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 18, 11, 55, 45, 780597, tzinfo=datetime.timezone.utc)),
        ),
    ]
