# Generated by Django 4.2.7 on 2024-03-09 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0045_alter_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 9, 15, 34, 54, 720131, tzinfo=datetime.timezone.utc), verbose_name='تاریخ نشر'),
        ),
    ]
