# Generated by Django 4.2.7 on 2024-03-21 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0047_alter_article_pub_date_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=200, verbose_name='اینستاگرام')),
                ('telegram', models.CharField(max_length=200, verbose_name='تلگرام')),
                ('whatsapp', models.CharField(max_length=200, verbose_name='واتساپ')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 21, 18, 24, 28, 207476, tzinfo=datetime.timezone.utc), verbose_name='تاریخ نشر'),
        ),
    ]
