# Generated by Django 4.2.7 on 2024-03-22 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0066_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 18, 18, 1, 60513, tzinfo=datetime.timezone.utc), verbose_name='تاریخ نشر'),
        ),
    ]
